#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function integration-test {
  $DIR/integration-test-template $@
}

integration-test aws-csharp 'apt-get -qq update && apt-get -qq -y install zip && dotnet restore && dotnet lambda package --configuration release --framework netcoreapp1.0 --output-package bin/release/netcoreapp1.0/deploy-package.zip'
integration-test aws-fsharp 'apt-get -qq update && apt-get -qq -y install zip && dotnet restore && dotnet lambda package --configuration release --framework netcoreapp1.0 --output-package bin/release/netcoreapp1.0/deploy-package.zip'
integration-test aws-groovy-gradle ./gradlew build
integration-test aws-java-gradle ./gradlew build
integration-test aws-java-maven mvn package
integration-test aws-scala-sbt sbt assembly
integration-test aws-nodejs
integration-test aws-python
integration-test aws-python3
integration-test aws-kotlin-jvm-gradle
integration-test aws-kotlin-jvm-maven
integration-test aws-kotlin-nodejs-gradle
integration-test aws-nodejs-typescript
integration-test aws-nodejs-ecma-script
integration-test google-nodejs
integration-test spotinst-nodejs
integration-test spotinst-python
integration-test spotinst-ruby
integration-test webtasks-nodejs
