#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function integration-test {
  $DIR/integration-test-template $@
}

integration-test aws-csharp 'apt-get -qq update && apt-get -qq -y install zip && dotnet restore && dotnet publish -c release && pushd bin/release/netcoreapp1.0/publish && zip -r ./deploy-package.zip ./* && popd'
integration-test aws-groovy-gradle ./gradlew build
integration-test aws-java-gradle ./gradlew build
integration-test aws-java-maven mvn package
integration-test aws-scala-sbt sbt assembly
integration-test aws-nodejs
integration-test aws-python
