#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function integration-test {
  $DIR/integration-test-template $@
}

integration-test aws-csharp './build.sh'
integration-test aws-fsharp './build.sh'
integration-test aws-go 'cd /go/src/app && make build'
integration-test aws-go-dep 'cd /go/src/app && make build'
integration-test aws-groovy-gradle ./gradlew build
integration-test aws-java-gradle ./gradlew build
integration-test aws-java-maven mvn package
integration-test aws-scala-sbt sbt assembly
integration-test aws-nodejs
integration-test aws-python
integration-test aws-python3
integration-test aws-kotlin-jvm-gradle
integration-test aws-kotlin-jvm-maven
integration-test aws-kotlin-nodejs-gradle
integration-test aws-nodejs-typescript
integration-test aws-nodejs-ecma-script
integration-test google-nodejs
integration-test spotinst-nodejs
integration-test spotinst-python
integration-test spotinst-ruby
integration-test spotinst-java8 mvn package
integration-test webtasks-nodejs
