export const ServerlessErrorCodes = {
  acm: {
    ACM_CERTIFICATE_VALIDATION_TIMEOUT: 'ACM_CERTIFICATE_VALIDATION_TIMEOUT',
  },
  alb: {
    FAILED_TO_CREATE_TARGET_GROUP: 'FAILED_TO_CREATE_TARGET_GROUP',
  },
  iam: {
    IAM_ROLE_NOT_FOUND: 'IAM_ROLE_NOT_FOUND',
  },
  containers: {
    FAILED_TO_CREATE_FARGATE_SERVICE: 'FAILED_TO_CREATE_FARGATE_SERVICE',
    FAILED_TO_STOP_FARGATE_SERVICE: 'FAILED_TO_STOP_FARGATE_SERVICE',
  },
  vpc: {
    FAILED_TO_CREATE_S2S_SECURITY_GROUP: 'FAILED_TO_CREATE_S2S_SECURITY_GROUP',
    FAILED_TO_CREATE_LOAD_BALANCER_SECURITY_GROUP:
      'FAILED_TO_CREATE_LOAD_BALANCER_SECURITY_GROUP',
  },
  lambda: {
    FAILED_TO_CREATE_LAMBDA_FUNCTION: 'FAILED_TO_CREATE_LAMBDA_FUNCTION',
    FAILED_TO_UPDATE_LAMBDA_FUNCTION: 'FAILED_TO_UPDATE_LAMBDA_FUNCTION',
  },
  compose: {
    COMPOSE_CONFIGURATION_NOT_PROVIDED: 'COMPOSE_CONFIGURATION_NOT_PROVIDED',
    COMPOSE_CONFIGURATION_INVALID: 'COMPOSE_CONFIGURATION_INVALID',
    COMPOSE_COMMAND_NOT_SUPPORTED: 'COMPOSE_COMMAND_NOT_SUPPORTED',
    COMPOSE_GRAPH_SERVICE_DEPENDENCY_DOES_NOT_EXIST:
      'COMPOSE_GRAPH_SERVICE_DEPENDENCY_DOES_NOT_EXIST',
    COMPOSE_GRAPH_CIRCULAR_DEPENDENCY: 'COMPOSE_GRAPH_CIRCULAR_DEPENDENCY',
    COMPOSE_COULD_NOT_RESOLVE_PARAM: 'COMPOSE_COULD_NOT_RESOLVE_PARAM',
    COMPOSE_PARAM_INVALID_FORMAT: 'COMPOSE_PARAM_INVALID_FORMAT',
    COMPOSE_ORG_PROPERTY_MISSING: 'COMPOSE_ORG_PROPERTY_MISSING',
    NESTED_COMPOSE_PROJECT: 'NESTED_COMPOSE_PROJECT',
    COMPOSE_STATE_INSUFFICIENT_PERMISSIONS:
      'COMPOSE_STATE_INSUFFICIENT_PERMISSIONS',
  },
  framework: {
    FRAMEWORK_CONFIG_NOT_FOUND: 'FRAMEWORK_CONFIG_NOT_FOUND',
    FRAMEWORK_VARIABLES_NOT_SUPPORTED_FOR_PROVIDER:
      'FRAMEWORK_VARIABLES_NOT_SUPPORTED_FOR_PROVIDER',
    FRAMEWORK_UNSUPPORTED_PROVIDER: 'FRAMEWORK_UNSUPPORTED_PROVIDER',
    MISMATCHED_COMPOSE_FRAMEWORK_ORG: 'MISMATCHED_COMPOSE_FRAMEWORK_ORG',
  },
  sam: {
    MISSING_STACK_NAME: 'MISSING_STACK_NAME',
    BUCKET_NOT_FOUND: 'BUCKET_NOT_FOUND',
    MISSING_DEPLOYMENT_BUCKET: 'MISSING_DEPLOYMENT_BUCKET',
    TEMPLATE_FILE_NOT_FOUND: 'TEMPLATE_FILE_NOT_FOUND',
    DEPLOY_FAILED: 'DEPLOY_FAILED',
    STACK_NOT_FOUND: 'STACK_NOT_FOUND',
    UNSUPPORTED_COMMAND: 'UNSUPPORTED_COMMAND',
    CLI_ERROR: 'CLI_ERROR',
  },
  general: {
    CONFIG_FILE_NOT_FOUND: 'CONFIG_FILE_NOT_FOUND',
    FAILED_TO_READ_CONFIG_FILE: 'FAILED_TO_READ_CONFIG_FILE',
    AUTH_METHOD_CANCELED: 'AUTH_METHOD_CANCELED',
    AUTH_METHOD_FAILED: 'AUTH_METHOD_FAILED',
    AUTH_FAILED: 'AUTH_FAILED',
    AWS_CREDENTIALS_MISSING: 'AWS_CREDENTIALS_MISSING',
    INVALID_CONFIG: 'INVALID_CONFIG',
    SERVICE_UNIQUE_ID_NOT_FOUND: 'SERVICE_UNIQUE_ID_NOT_FOUND',
    COMMAND_BLOCKED_BY_NOTIFICATION: 'COMMAND_BLOCKED_BY_NOTIFICATION',
  },
  deployments: {
    FUNCTION_PARAM_MISSING: 'FUNCTION_PARAM_MISSING',
    SUBSCRIPTION_PARAM_MISSING: 'SUBSCRIPTION_PARAM_MISSING',
  },
  resolvers: {
    RESOLVER_MANAGER_NOT_FOUND: 'RESOLVER_MANAGER_NOT_FOUND',
    RESOLVER_PROVIDER_NOT_SUPPORTED: 'RESOLVER_PROVIDER_NOT_SUPPORTED',
    RESOLVER_NOT_FOUND: 'RESOLVER_NOT_FOUND',
    RESOLVER_RESOLVE_VARIABLE_ERROR: 'RESOLVER_RESOLVE_VARIABLE_ERROR',
    RESOLVER_INVALID_CONFIG: 'RESOLVER_INVALID_CONFIG',
    RESOLVER_NON_STRING_VARIABLE_RESULT: 'RESOLVER_NON_STRING_VARIABLE_RESULT',
    RESOLVER_NO_VARIABLES_FOUND: 'RESOLVER_NO_VARIABLES_FOUND',
    RESOLVER_MISSING_VARIABLE_RESULT: 'MISSING_VARIABLE_RESULT',
    RESOLVER_NON_STRING_CONFIG_KEY: 'RESOLVER_NON_STRING_CONFIG_KEY',
    RESOLVER_CYCLIC_REFERENCE: 'RESOLVER_CYCLIC_REFERENCE',
    RESOLVER_INVALID_PLUGIN_CONFIGURATION:
      'RESOLVER_INVALID_PLUGIN_CONFIGURATION',
    RESOLVER_NAME_DUPLICATE: 'RESOLVER_NAME_DUPLICATE',
  },
  axiom: {
    AXIOM_TOKEN_NOT_FOUND: 'AXIOM_TOKEN_NOT_FOUND',
    AXIOM_CREATE_DATASET_FAILED: 'AXIOM_CREATE_DATASET_FAILED',
    AXIOM_INITIALIZE_DATASET_FAILED: 'AXIOM_INITIALIZE_DATASET_FAILED',
    AXIOM_ALREADY_INTEGRATED_WITH_DASHBOARD:
      'AXIOM_ALREADY_INTEGRATED_WITH_DASHBOARD',
    AXIOM_DASHBOARD_CHECK_FAILED: 'AXIOM_DASHBOARD_CHECK_FAILED',
    AXIOM_GITHUB_TOKEN_INVALID: 'AXIOM_GITHUB_TOKEN_INVALID',
  },
  state: {
    STATE_VERSIONING_CHECK_FAILED: 'STATE_VERSIONING_CHECK_FAILED',
  },
  globalBucket: {
    GLOBAL_BUCKET_GET_SSM_PARAMETER_FAILED:
      'GLOBAL_BUCKET_GET_SSM_PARAMETER_FAILED',
  },
  deploymentBucket: {
    DEPLOYMENT_BUCKET_INSUFFICIENT_PERMISSIONS:
      'DEPLOYMENT_BUCKET_INSUFFICIENT_PERMISSIONS',
  },
  kontinuum: {
    KONTINUUM_INVALID_CONFIG: 'KONTINUUM_INVALID_CONFIG',
    KONTINUUM_ECR_LOGIN_FAILED: 'KONTINUUM_ECR_LOGIN_FAILED',
    KONTINUUM_ECR_CREATE_REPOOSITORY_FAILED:
      'KONTINUUM_ECR_CREATE_REPOOSITORY_FAILED',
    KONTINUUM_VPC_CREATE_FAILED: 'KONTINUUM_VPC_CREATE_FAILED',
    KONTINUUM_ECS_CLUSTER_CREATE_FAILED: 'KONTINUUM_ECS_CLUSTER_CREATE_FAILED',
    KONTINUUM_FUNCTION_ARN_NOT_FOUND: 'KONTINUUM_FUNCTION_ARN_NOT_FOUND',
    KONTINUUM_SUBNET_CREATE_FAILED: 'KONTINUUM_SUBNET_CREATE_FAILED',
    KONTINUUM_INTERNET_GATEWAY_CREATE_FAILED:
      'KONTINUUM_INTERNET_GATEWAY_CREATE_FAILED',
    KONTINUUM_INTERNET_GATEWAY_ATTACH_FAILED:
      'KONTINUUM_INTERNET_GATEWAY_ATTACH_FAILED',
  },
  route53: {
    NO_MATCHING_HOSTED_ZONE: 'NO_MATCHING_HOSTED_ZONE',
    ROUTE53_LIST_HOSTED_ZONES_FAILED: 'ROUTE53_LIST_HOSTED_ZONES_FAILED',
    ROUTE53_CERTIFICATE_VALIDATION_RECORDS_FAILED:
      'ROUTE53_CERTIFICATE_VALIDATION_RECORDS_FAILED',
    ROUTE53_RECORD_CHANGE_FAILED: 'ROUTE53_RECORD_CHANGE_FAILED',
    ROUTE53_HOSTED_ZONE_NOT_FOUND: 'ROUTE53_HOSTED_ZONE_NOT_FOUND',
  },
  domains: {
    DOMAIN_VALIDATION_INCOMPATIBLE_ENDPOINT_TYPE:
      'DOMAIN_VALIDATION_INCOMPATIBLE_ENDPOINT_TYPE',
    DOMAIN_CREATION_FAILED: 'DOMAIN_CREATION_FAILED',
    DOMAIN_DELETION_FAILED: 'DOMAIN_DELETION_FAILED',
    DOMAIN_CONFIG_INVALID_ENDPOINT_TYPE: 'DOMAIN_CONFIG_INVALID_ENDPOINT_TYPE',
    DOMAIN_CONFIG_INVALID_API_TYPE: 'DOMAIN_CONFIG_INVALID_API_TYPE',
    DOMAIN_CONFIG_MULTIPLE_API_TYPES_DETECTED:
      'DOMAIN_CONFIG_MULTIPLE_API_TYPES_DETECTED',
    DOMAIN_CONFIG_INVALID_TLS_TRUSTSTORE_URI:
      'DOMAIN_CONFIG_INVALID_TLS_TRUSTSTORE_URI',
    DOMAIN_CONFIG_INVALID_SECURITY_POLICY:
      'DOMAIN_CONFIG_INVALID_SECURITY_POLICY',
    DOMAIN_CONFIG_INVALID_ROUTING_POLICY:
      'DOMAIN_CONFIG_INVALID_ROUTING_POLICY',
    DOMAIN_CONFIG_ROUTING_POLICY_EDGE_INCOMPATIBLE:
      'DOMAIN_CONFIG_ROUTING_POLICY_EDGE_INCOMPATIBLE',
    DOMAIN_CONFIG_AMBIGUOUS_BOOLEAN: 'DOMAIN_CONFIG_AMBIGUOUS_BOOLEAN',
    ACM_CERTIFICATE_SEARCH_FAILED: 'ACM_CERTIFICATE_SEARCH_FAILED',
    ACM_CERTIFICATE_NOT_FOUND: 'ACM_CERTIFICATE_NOT_FOUND',
    ACM_CERTIFICATE_CREATION_FAILED: 'ACM_CERTIFICATE_CREATION_FAILED',
    ACM_CERTIFICATE_VALIDATION_RECORDS_FAILED:
      'ACM_CERTIFICATE_VALIDATION_RECORDS_FAILED',
    ACM_CERTIFICATE_VALIDATION_RECORDS_TIMEOUT:
      'ACM_CERTIFICATE_VALIDATION_RECORDS_TIMEOUT',
    ACM_CERTIFICATE_VALIDATION_FAILED: 'ACM_CERTIFICATE_VALIDATION_FAILED',
    ACM_CERTIFICATE_VALIDATION_TIMEOUT: 'ACM_CERTIFICATE_VALIDATION_TIMEOUT',
    API_GATEWAY_CUSTOM_DOMAIN_CREATION_FAILED:
      'API_GATEWAY_CUSTOM_DOMAIN_CREATION_FAILED',
    API_GATEWAY_CUSTOM_DOMAIN_FETCH_FAILED:
      'API_GATEWAY_CUSTOM_DOMAIN_FETCH_FAILED',
    API_GATEWAY_CUSTOM_DOMAIN_DELETION_FAILED:
      'API_GATEWAY_CUSTOM_DOMAIN_DELETION_FAILED',
    API_GATEWAY_BASE_PATH_MAPPING_CREATION_FAILED:
      'API_GATEWAY_BASE_PATH_MAPPING_CREATION_FAILED',
    API_GATEWAY_BASE_PATH_MAPPING_FETCH_FAILED:
      'API_GATEWAY_BASE_PATH_MAPPING_FETCH_FAILED',
    API_GATEWAY_BASE_PATH_MAPPING_UPDATE_FAILED:
      'API_GATEWAY_BASE_PATH_MAPPING_UPDATE_FAILED',
    API_GATEWAY_BASE_PATH_MAPPING_DELETION_FAILED:
      'API_GATEWAY_BASE_PATH_MAPPING_DELETION_FAILED',
    CLOUDFORMATION_STACK_RESOURCE_NOT_FOUND:
      'CLOUDFORMATION_STACK_RESOURCE_NOT_FOUND',
    CLOUDFORMATION_API_ID_NOT_FOUND: 'CLOUDFORMATION_API_ID_NOT_FOUND',
    CLOUDFORMATION_DESCRIBE_STACK_FAILED:
      'CLOUDFORMATION_DESCRIBE_STACK_FAILED',
    S3_TLS_CERTIFICATE_OBJECT_NOT_FOUND: 'S3_TLS_CERTIFICATE_OBJECT_NOT_FOUND',
  },
}

/**
 * A custom error class for Serverless Framework errors
 * @class ServerlessError
 * @extends {Error}
 * @param {string} message - The error message
 * @param {string} code - The error code
 * @param {Object} options - Additional options
 * @param {string} options.originalMessage - The original error message that the ServerlessError is handling
 * @param {string} options.originalName - The original error name that the ServerlessError is handling
 * @param {boolean} options.stack - Whether to include the stack trace
 */
export class ServerlessError extends Error {
  constructor(message, code, options = {}) {
    super(message)
    this.code = code
    this.originalMessage = options.originalMessage
    this.originalName = options.originalName
    if (options.stack === false) {
      this.stack = undefined
    }
  }
}
