name: 🐛 Bug Report
description: Create a Bug Report. If you're using V.4, get priority support directly from our team by emailing us at support AT serverless.com
body:
  - type: textarea
    attributes:
      label: Issue description
      description: |
        Describe your issue here. If you are using V.4 and on a Serverless Subscription, you can get support directly from our team by emailing us at support AT serverless.com.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Context
      description: |
        Please include your Serverless Framework version, your serverless.yml (with any secrets redacted), the full command you ran, and the complete error output (re-run with the --debug flag for a stack trace).
        If not applicable, fill with "N/A"
    validations:
      required: false
