// Assuming these are your imports from individual files
import { getAwsCredentialProvider } from './credentials/index.js'
import {
  generateShortId,
  getCliOption,
  getHumanFriendlyTime,
  diffObjects,
  scrambleSensitiveValue,
} from './general/index.js'
import {
  fileExists,
  dirExists,
  readFile,
  writeFile,
  isNotSymbolicLink,
  copyDirContents,
  removeFileOrDirectory,
  parseDeclarativeConfig,
  renameTemplateInAllFiles,
  renameDirectory,
  getConfigFilePath,
  unzipFile,
  getRcConfig,
  saveRcAuthenticatedUser,
  saveRcAccessKeyV2,
  removeRcUserSession,
  removeRcAccessKeyV2,
  getDotServerlessLocalPath,
  getDotServerlessGlobalPath,
  writeAwsCredentialsToFile,
  getVersions,
  getRcNotificationLastShown,
  setRcNotificationLastShown,
} from './fs/index.js'
import { getConfigFileDetails } from './fs/config-file.js'
import { downloadTemplate, parseRepoURL } from './https/index.js'

// Export the combined object as default
export {
  getAwsCredentialProvider,
  generateShortId,
  getHumanFriendlyTime,
  diffObjects,
  getCliOption,
  fileExists,
  dirExists,
  readFile,
  writeFile,
  isNotSymbolicLink,
  copyDirContents,
  removeFileOrDirectory,
  scrambleSensitiveValue,
  parseDeclarativeConfig,
  renameTemplateInAllFiles,
  renameDirectory,
  getConfigFilePath,
  unzipFile,
  getRcConfig,
  saveRcAuthenticatedUser,
  saveRcAccessKeyV2,
  removeRcUserSession,
  removeRcAccessKeyV2,
  getDotServerlessLocalPath,
  getDotServerlessGlobalPath,
  writeAwsCredentialsToFile,
  getVersions,
  getRcNotificationLastShown,
  setRcNotificationLastShown,
  downloadTemplate,
  parseRepoURL,
  getConfigFileDetails,
}
