service: offline-rest-crud

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: items
          method: post
      - http:
          path: items
          method: get
      - http:
          path: items/{id}
          method: get
