name: Trigger Sync Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Trigger Sync Docs Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            console.log(`Triggering sync-docs workflow for stage: ${{ github.event.inputs.stage || 'dev' }}`);
            await github.rest.actions.createWorkflowDispatch({
              owner: 'serverlessinc',
              repo: 'growth',
              workflow_id: 'sync-docs.yml', // Replace with the actual workflow file name in the target repo
              ref: 'main',
              inputs: {
                stage: '${{ github.event.inputs.stage || 'dev' }}'
              }
            });
